spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/student_performance_dossier
    username: postgres
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true